package com.adlitteram.redit.draganddrop;

import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import javax.swing.JComponent;
import javax.swing.TransferHandler;

public class ArticlePanelTransHandler extends TransferHandler {

   public ArticlePanelTransHandler() {
      super();
   }

   @Override
   public int getSourceActions(JComponent c) {
      return COPY_OR_MOVE;
   }

   // Called after a drag was generated by the drawing area
   @Override
   protected void exportDone(JComponent comp, Transferable t, int action) {
   }

   // Copy/Export from component
   @Override
   protected Transferable createTransferable(JComponent comp) {
      return ImageFileListData.createTransferable(comp);
   }

   @Override
   public boolean canImport(JComponent comp, DataFlavor flavors[]) {
      return ArticleFileListData.canImport(comp, flavors)
              || ImageFileListData.canImport(comp, flavors);
   }

   // Paste/drop
   @Override
   public boolean importData(JComponent comp, Transferable t) {
      return ArticleFileListData.importData(comp, t)
              || ImageFileListData.importData(comp, t);
   }
}
