package com.adlitteram.redit.draganddrop;

import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import javax.swing.JComponent;
import javax.swing.TransferHandler;

public class ThumbListTransHandler extends TransferHandler {

   public ThumbListTransHandler() {
      super();
   }

   @Override
   public int getSourceActions(JComponent c) {
      return COPY_OR_MOVE;
   }

   // Called after a drag was generated by the drawing area 
   @Override
   protected void exportDone(JComponent comp, Transferable t, int action) {
   }

   @Override
   public boolean canImport(JComponent comp, DataFlavor flavors[]) {
      return false;
   }

   // Copy
   @Override
   protected Transferable createTransferable(JComponent comp) {
      return ImageFileListData.createTransferable(comp);
   }

   // Paste/drop
   @Override
   public boolean importData(JComponent comp, Transferable t) {
      return false;
   }
}
